
INSERT INTO role (NAME) VALUES("PRODUCT_SELECT");
INSERT INTO role (NAME) VALUES("PRODUCT_INSERT");
INSERT INTO role (NAME) VALUES("PRODUCT_UPDATE");
INSERT INTO role (NAME) VALUES("PRODUCT_DELETE");

